// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaa-oULWFXeEwdupNVj3yVsW1EsRmIgU',
    appId: '1:920845460436:web:0b8d1ecd59006cea31ec41',
    messagingSenderId: '920845460436',
    projectId: 'grocergease',
    authDomain: 'grocergease.firebaseapp.com',
    storageBucket: 'grocergease.firebasestorage.app',
    measurementId: 'G-4J5FMLDZ8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJGvc6EV_Mbx6ai7PVsGd3BxAufqhIxjU',
    appId: '1:920845460436:android:c5ab896ac386ab0e31ec41',
    messagingSenderId: '920845460436',
    projectId: 'grocergease',
    storageBucket: 'grocergease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ4Cd3LwPiiBazW45XwZEBTKUqXEG1RvE',
    appId: '1:920845460436:ios:fcd891195949f72a31ec41',
    messagingSenderId: '920845460436',
    projectId: 'grocergease',
    storageBucket: 'grocergease.firebasestorage.app',
    iosClientId: '920845460436-f6u8q62dvhbcj499b0attob630maaebe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ4Cd3LwPiiBazW45XwZEBTKUqXEG1RvE',
    appId: '1:920845460436:ios:fcd891195949f72a31ec41',
    messagingSenderId: '920845460436',
    projectId: 'grocergease',
    storageBucket: 'grocergease.firebasestorage.app',
    iosClientId: '920845460436-f6u8q62dvhbcj499b0attob630maaebe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaa-oULWFXeEwdupNVj3yVsW1EsRmIgU',
    appId: '1:920845460436:web:3458e38c5483405e31ec41',
    messagingSenderId: '920845460436',
    projectId: 'grocergease',
    authDomain: 'grocergease.firebaseapp.com',
    storageBucket: 'grocergease.firebasestorage.app',
    measurementId: 'G-B2WJKLKNHQ',
  );

}